### ISSUE TITLE
Clicking on a project does nothing

### ISSUE THREAD

**Issue by jdgarvey** [davidavila2/resolver-guard#10]
When I click on a project nothing happens... I have to click the three dots to go to the details page. 
Also related, having 3 dots doesn't make sense if there isn't a menu there.
![image](https://user-images.githubusercontent.com/1544557/148423955-df33ac2c-ba7d-4f33-89a3-d853242b0992.png)

**Comment by davidavila2** [comment]
Fixed, I was thinking the same thing
