### ISSUE TITLE
Confirmation popup shows up no matter what

### ISSUE THREAD

**Issue by jdgarvey** [davidavila2/resolver-guard#11]
When I navigate to the edit screen of a project, then navigate away from the screen, even if I've made no changes I still get the "you'll lose all your changes" dialog. I should only get that if I've actually made changes. 

Also, when I click "Save" when I'm adding or editing a project, it gives me that same popup. Don't need that popup when I'm saving or editing.

Also, the capitalization needs to be fixed, and it should be phrased as a question... something like "There are unsaved changes to your project. Are you sure you want to leave this page?"

![image](https://user-images.githubusercontent.com/1544557/148424366-5507294f-c55c-4303-b5de-9f7eec85cded.png)

**Comment by davidavila2** [comment]
I believe this was fixed when I fixed the boolean issue
