### ISSUE TITLE
Skip resolver

### ISSUE THREAD

**Issue by jdgarvey** [davidavila2/resolver-guard#5]
Why do you skip the resolver here? I went and looked at the route in question and there is no resolver.
Also, formatting issue.

https://github.com/davidavila2/resolver-guard/blob/0d669fab807b147f422f32257178dc1fec30be56/apps/dashboard/src/app/projects/project-list/project-list.component.ts#L18-L25

**Comment by davidavila2** [comment]
I went ahead a removed it, I added this for testing and forgot to remove
